### ISSUE TITLE
cURL error 35: OpenSSL SSL_connect: Connection reset by peer

### ISSUE THREAD

**Issue by CirruZZ** [walle89/SwedbankJson#52]
Juste received this error trying to initiate an authentication process. Nothing (code) have change from mys side, ie, the code I'm using have worked a week ago.

`cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to auth.api.swedbank.se:443 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**Comment by walle89** [comment]
Hi,

I tried myself now and it works for me.

These kind of errors are in most cases network or environment related. 

**My best guess are these postnasal issues:**
- If the environment you run the PHP script from have issues with resolving auth.api.swedbank.se. So dubble check you have working DNS settings and test if it can do DNS lookups. 
- Have issues with connecting to the internet
- Some temporarily issue out of you control, e.g. on Swedbank's end.

In theory, even if I haven't observed this behavior from Swedbank, it's possible you could got this because the IP is blocked (temporarily) by Swedbank due to rate limiting or similar.

**Comment by CirruZZ** [comment]
FYI.
I have been testing for a while now, only was a few days I had the problem. It seemed to be something with the generation/retrieval of the QR code, but it was intermittent. After a few days, everything worked as it should, and the problem was gone. Nothing changed on my side. Can't tell what the issue was.
